build-container:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  image: docker:latest
  services:
    - docker:dind
  before_script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.gitlab.com
  script:
      - docker buildx create --use
      - docker buildx build --push -t "registry.gitlab.com/makkes/e13-website:$CI_COMMIT_TAG" --platform linux/amd64,linux/arm64 .
